name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sign
        run: |
          ./sign.sh
